module.exports = {
	FOLDER_CONTENT_ARRIVED: 'FOLDER_CONTENT_ARRIVED',
	SORT_FILES: 'SORT_FILES',
	FILTER_FILES: 'FILTER_FILES',

	SORT_BY_TITLE: 'SORT_BY_TITLE',
	SORT_BY_STATUS: 'SORT_BY_STATUS',
	SORT_BY_TYPE: 'SORT_BY_TYPE',
	SORT_BY_CREATED: 'SORT_BY_CREATED',
	SORT_BY_MODIFIED: 'SORT_BY_MODIFIED',
};
